export ZSH=/home/{{user}}/.oh-my-zsh
ZSH_THEME="robbyrussell"
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git virtualenvwrapper)
source $ZSH/oh-my-zsh.sh
export LANG=en_US.UTF-8

Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='mvim'
fi
source ~/.bash_aliases
